services:
  postgres:
    image: 'postgres:16'
    environment:
      POSTGRES_DB: "fisfleet-db"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
    volumes:
      - ./src/main/resources/db:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
